export const LOGIN_USER = 'login_user';
export const REGISTER_USER = 'register_user';
export const AUTH_USER = 'auth_user';
export const LOGOUT_USER = 'logout_user';
export const NAME_USER='name_user';
export const PASSWORD_USER='password_user';
export const DELETE_TEST="delete_test";
export const REGISTER_SUMMARY="register_user";
export const REGISTER_AI="register_ai";
export const GET_SUMMARY="get_summary";
export const GET_MY_SUMMARY="get_my_summary"
